### ISSUE TITLE
Is alert not the right function to use to show content?

### ISSUE THREAD

**Issue by C-G-G** [C-G-G/phrasal-template-generator#1]
I used `alert()` to show the first sentence but Markbot is not happy about it. Is there a better function or another way to show content? Thanks.

@thomasjbradley 

<img width="783" alt="Screen Shot 2021-10-15 at 1 41 20 AM" src="https://user-images.githubusercontent.com/16348315/137438254-e751695b-019b-41fd-89a2-ad69343fff21.png">

**Comment by thomasjbradley** [comment]
It’s probably that the apostrophe in the text you wrote is incorrect. Copy and paste this one: `’`
